xsbti.compile.IncOptions does not have copy method
https://github.com/sbt/zinc/blob/v1.0.3/internal/compiler-interface/src/main/contraband-java/xsbti/compile/IncOptions.java#L225

```
sample-project > set incOptions := incOptions.value.copy(apiDebug = true)
<set>:1: error: value copy is not a member of xsbti.compile.IncOptions
incOptions := incOptions.value.copy(apiDebug = true)
                               ^
<set>:1: error: not found: value apiDebug
incOptions := incOptions.value.copy(apiDebug = true)
                                    ^
[error] Type error in expression
```