fix ShellPrompPlugin.scala compile errors/warning (#464)
```
[error] project/ShellPrompPlugin.scala:10:16: not found: type ProcessLogger
[error]   val devnull: ProcessLogger = new ProcessLogger {
[error]                ^
[error] project/ShellPrompPlugin.scala:10:36: not found: type ProcessLogger
[error]   val devnull: ProcessLogger = new ProcessLogger {
[error]                                    ^
[error] project/ShellPrompPlugin.scala:16:23: value lines_! is not a member of String
[error]     ("git status -sb" lines_! devnull headOption)
[error]                       ^
[error] three errors found
[error] (compile:compileIncremental) Compilation failed
```

```
project/ShellPrompPlugin.scala:11:36: object creation impossible, since:
[error] it has 2 unimplemented members.
[error] /** As seen from <$anon: scala.sys.process.ProcessLogger>, the missing signatures are as follows.
[error]  *  For convenience, these are usable as stub implementations.
[error]  */
[error]   def err(s: => String): Unit = ???
[error]   def out(s: => String): Unit = ???
[error]   val devnull: ProcessLogger = new ProcessLogger {
[error]                                    ^
```